export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as List } from './List'
export { default as AddCategory } from './AddCategory'
export { default as EditCategory } from './EditCategory'